name: Specific setup for connector
description: Starts a postgres database for unit tests
runs:
  using: "composite"
  steps:
    - name: Start local postgres server with Docker
      if: runner.os == 'Linux'
      shell: bash
      run: |
       docker pull postgres
       docker run --name my-postgres --env POSTGRES_PASSWORD=${{env.POSTGRES_PW}} --publish 5432:5432 --detach postgres
