name: Specific setup for connector
description: Starts a postgres database for unit tests
runs:
  using: "composite"
  steps:
    - name: Start local postgres server with Docker
      if: runner.os == 'Linux'
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: docker compose -f "$ACTION_PATH/docker-compose.yaml" up --detach
