name: Specific setup for connector
description: Starts a postgres database for unit tests
runs:
  using: "composite"
  steps:
    - name: Start local postgres server with Docker
      if: runner.os == 'Linux'
      shell: bash
      run: docker compose -f "${{ github.action_path }}/docker-compose.yaml" up --detach
