---
title: "How to extend connector"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to extend connector}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(connector)
```

TODO: This is a vignette describing how to use the s3 dispatch to create your own 
methods, and how to create your own connector classes.

```{r, eval = FALSE}
# Description from old connector_methods docs. To be rewritten for this vignette:
#' Defaults methods for all connector object
#'
#' @description
#' These methods are a S3 method that dispatches to the specific methods for the connector object.
#'
#' @details
#' For example, if you have a connector object `connector_fs`, you can use `read_cnt(connector_fs, "file.csv")`
#' to read the file. It will be dispatch to the `read_cnt.connector_fs` method.
#' Why? The main aim is to allow the user to use the same function for different connector objects by
#' using the builder function `connector_fs` and add an "extra_class".
#' By doing so, you can create a subclass of the `connector_fs` object and
#' dispatch to the specific methods for this subclass.
#' For example, if you have a subclass `subclass`, you can use `cnr_read(subclass, "file.csv")` to read the file.
#' It will be dispatch to the `read_cnt.subclass` method. And you can still use the `connector_fs` methods.
#'
#' @param connector_object A connector object to be able to use functions from it
#' @param ... Additional arguments passed to the method
#' @name connector_methods
NULL
```

