# An example of the configuration file for FS
metadata:
  tmp_dir_path: !expr tempdir()

connections:
  - con: "adam"
    backend:
      type: "connector_fs"
      path: "{metadata.tmp_dir_path}/adam"
  - con: "tfl"
    backend:
      type: "connector_fs"
      path: "{metadata.tmp_dir_path}/tfl"

datasources:
  - name: "adam"
    con: "adam"
  - name: "tfl"
    con: "tfl"
