# An example of the configuration file for FS
metadata:
  tmp_dir_path: !expr tempdir()

datasources:
  - name: "adam"
    backend:
      type: "ConnectorFS"
      path: "{metadata.tmp_dir_path}/adam"
  - name: "tfl"
    backend:
      type: "ConnectorFS"
      path: "{metadata.tmp_dir_path}/tfl"
